---
- name: Add PPA repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP component
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.1 
    - php7.1-cli 
    - php7.1-common 
    - php7.1-json 
    - php7.1-opcache 
    - php7.1-mysql 
    - php7.1-mbstring 
    - php7.1-mcrypt 
    - php7.1-zip 
    - php7.1-fpm