---
- name: Copy nginx conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy wordpress conf
  template:
    src: templates/sites-available/wordpress.j2
    dest: /etc/nginx/sites-available/wordpress